# Basic

In [1]:
import pandas as pd

## Series

In [2]:
l1 = [1,2,3,5,7,8]
pd.Series(l1)

0    1
1    2
2    3
3    5
4    7
5    8
dtype: int64

In [3]:
d1 = {"america": 10, 
     "europe": 20,
     "mena": 15, 
     "asia": 3
     }

In [4]:
pd.Series(d1)

america    10
europe     20
mena       15
asia        3
dtype: int64

## DataFrames

### Create from Dictionary

In [5]:
d1 = {"PIB":
    {"europe":1, 
      "latin-america": 3, 
      "mena":6, 
      "asia":8
     }
}

df = pd.DataFrame.from_dict(d1, orient="index").T
df

               PIB
europe           1
latin-america    3
mena             6
asia             8

### Add Rows

In [6]:
df.loc[len(df)] = [7]
df.rename(index={df.index[-1]:"oceania"}, inplace=True)
df

               PIB
europe           1
latin-america    3
mena             6
asia             8
oceania          7

In [7]:
for row in df.iterrows():
    print(row[0], row[1].PIB)

europe 1
latin-america 3
mena 6
asia 8
oceania 7

In [8]:
for label, content in df.items():
    print("Label", label) 
    print("Content", content)

Label PIB
Content europe           1
latin-america    3
mena             6
asia             8
oceania          7
Name: PIB, dtype: int64

In [9]:
leverage = lambda x, p: x*p

In [11]:
df.apply(leverage, args=(15, ))

               PIB
europe          15
latin-america   45
mena            90
asia           120
oceania        105